GROQ_API_KEY = "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"

ARIZE_SPACE_ID = "U3BhY2U6NDA3ODg6emJ2Rw=="

ARIZE_API_KEY = "ak-679b43ea-eb54-42f6-b8ba-e37345071856-LANWVC4IBYFeS5V7O9BILE7xu0LrU47l"
